version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    networks:
      - rennlabs

  nextjs:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: nextjs_container
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: [sh, -c, '${START_COMMAND}']

volumes:
  postgres_data:

networks:
  rennlabs:
    driver: bridge
